version: "3.8"

services:
  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafiotriagildb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/desafiotriagil
    container_name: desafiotriagil
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/desafiotriagildb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
